baseURL: https://blog.nacly.net/
languageCode: en-us
title: HKC
theme: "PaperMod"

params:
  disableThemeToggle: true
  mainSections: about

menu:
    main:
        - identifier: guides
          name: guides
          url: /guides/
          weight: 10
        - identifier: posts
          name: posts
          url: /posts/
          weight: 20
        - identifier: shop
          name: shop
          url: https://shop.nacly.net
          weight: 40
        - identifier: group buys
          name: group buys
          url: /gbs/
          weight: 40
        - identifier: about
          name: about
          url: /about/
          weight: 50
